### ISSUE TITLE
Foto e testo sottosezione ristorante

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#11]

**Comment by LetiGale** [comment]
Testo seconda parte sezione ristorante:

Giordano Calcina, chef gourmet d’eccellenza, approda nella cucina del Light House vantando un altissimo background culinario maturato in esclusivi ristoranti e alberghi internazionali.
Da sempre legato alle tradizioni, lo chef propone una riscoperta della cucina marchigiana per condividere con i suoi ospiti gusti e sapori del territorio, equilibrando al tempo stesso bellezza estetica e piacere del gusto.
L’accurata presentazione dei suoi piatti e gli intensi aromi, sono soliti annunciare alla vista e all’olfatto un’esperienza che sarà sublime per il palato.
