### ISSUE TITLE
Booking

### ISSUE THREAD

**Issue by LetiGale** [mauriziocingolani/seeport#14]
Sistemare sezione booking in modo che dal riquadro "prenota" si viene reindirizzati ad un'altra pagina con booking engine.

**Comment by GiorgioGnoli** [comment]
Ciao Maurizio, questo è lo screenshot del booking. 
potremmo inserire uno spazio tra camere e check in?

Poi sul tipo di camere possiamo direttamente inserire il nome (non credo sia prioritario adesso pensare ai prezzi)?

Grazie

![booking](https://cloud.githubusercontent.com/assets/9283377/4770401/70feeb74-5b85-11e4-888b-c941e32746c3.PNG)
