### ISSUE TITLE
Testo form contatti

### ISSUE THREAD

**Issue by LetiGale** [mauriziocingolani/seeport#22]
Testo da inserire vicino alla forma contatti:

Per contattare il SeePort Hotel compila il form seguente.

Il num di telefono se puoi eliminalo perchè non lo sappiamo ancora, l'apertura dell'hotel è h24, email sito e localizzazione le sai già.

**Comment by mauriziocingolani** [comment]
24/7 lo capiranno? Meglio h24 ?

**Comment by LetiGale** [comment]
Meglio h24
