### ISSUE TITLE
Invio email di conferma ricevuta prenotazione al cliente

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#25]

**Comment by mauriziocingolani** [comment]
Da valutare se inviare al cliente una mail di conferma.
Semmai ci pensate voi al testo?

**Comment by LetiGale** [comment]
Gentile Sig. (cognome), grazie per aver scelto il SeePort Hotel.
Stiamo verificando la disponibilità per le date da lei richieste, la contatteremo al più presto.
Lo staff del SeePort Hotel.

_Inserire logo_
