### ISSUE TITLE
Links social

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#27]

**Comment by LetiGale** [comment]
Twitter:    https://twitter.com/

**Comment by mauriziocingolani** [comment]
Sicura? Questa è la home page di twitter, non la pagina del seeport ;-)

**Comment by GiorgioGnoli** [comment]
https://twitter.com/SeePortHotel perdonala...è innamorata

**Comment by LetiGale** [comment]
:P 
g+ ----> https://plus.google.com/b/108942651145480779794/dashboard/overview

**Comment by GiorgioGnoli** [comment]
Facebook
https://www.facebook.com/seeporthotel?ref=hl
