### ISSUE TITLE
Informativa privacy generale

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#39]

**Comment by GiorgioGnoli** [comment]
Leti per favore puoi far pressioni al consulente per avere l'informativa aggiornata?

**Comment by GiorgioGnoli** [comment]
Il file Word "INF04_03_PrivacyPolicyWeb" contiene l'informativa sulla privacy aggiornata. Può essere caricato un PDF e linkare ad esso o, alternativamente si può copiare tutto il contenuto nel popup, sostituendo quello che già c'è

**Comment by GiorgioGnoli** [comment]
Ho controllato la privacy e non ci sono sfrondoni ;) chiusa anche questa
