### ISSUE TITLE
Gallery responsive per immagini

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#40]
Modificare gallery foto camere e servizi per gestire meglio la responsività
io ne ho trovato anche uno in bootstrap
http://www.jssor.com/
http://plugins.jquery.com/blueimp-bootstrap-image-gallery/

fammi sapere se servono altre fonti

**Comment by mauriziocingolani** [comment]
Allora, la prima non è una gallery a pop-up.
La seconda potrebbe andare, ma per integrarla ci devo lavorare un po'.
Siamo sicuri che va bene? Forse è il caso di sentire prima Guido?

**Comment by GiorgioGnoli** [comment]
Ciao Mauri ho visto Guido e gli ho mostrato la gallery n2. Ha detto che va bene anche vista da mobile quindi io andrei su quella

**Comment by mauriziocingolani** [comment]
Ok la sistemo oggi pomeriggio

**Comment by mauriziocingolani** [comment]
http://www.seeporthotel.com/index_1.php

Gallery attiva sulle camere.
Se va bene la replico per i servizi e la pubblico
