### ISSUE TITLE
Inserire Link nella sezione Location

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#46]
Inserire Link che rimandi a Contatti dietro al testo via XXIX Settembre

inserire anche grassetto su "porto di Ancona", subito dopo

**Comment by mauriziocingolani** [comment]
Scusa non ho capito cosa intendi per "dietro". Il link deve essere sulle parole "via XXIX Settembre"?

**Comment by GiorgioGnoli** [comment]
sì esatto
