### ISSUE TITLE
Cambiare foto

### ISSUE THREAD

**Issue by LetiGale** [mauriziocingolani/seeport#49]
Tipologia di stanza superior: 
![img_7877_b](https://cloud.githubusercontent.com/assets/9284701/4938761/ba20c226-65cd-11e4-8f42-e86f2894b3fe.jpg)

Tipologia di stanza Executive:
![img_7884_b](https://cloud.githubusercontent.com/assets/9284701/4938771/d0c1fd56-65cd-11e4-8ee0-55e7dd4e64c0.jpg)

**Comment by mauriziocingolani** [comment]
Le immagini delle camere devono essere di due formati precisi:
- 235x250 pixel quelle piccole
- 830x550 pixel quelle che aprono cliccando

Potete farle rifare da Tommy?
