### ISSUE TITLE
Modifica etichetta ristorante sulla Home

### ISSUE THREAD

**Issue by LetiGale** [mauriziocingolani/seeport#50]
![ristorante bandierina3](https://cloud.githubusercontent.com/assets/9284701/4939127/8a6e4866-65d0-11e4-8b63-5626d713e48d.png)

**Comment by mauriziocingolani** [comment]
Ho caricato l'immagine ma non mi sembra che si veda granchè.
Vedete voi se lasciarla così o rifarla.

**Comment by GiorgioGnoli** [comment]
Guido ha detto che l'etichetta con Ginevra va bene
