### ISSUE TITLE
Versione EN del sito

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#51]
Creare il sito in inglese, se possibile chiamandolo www.seeporthotel.com/en e inserire il copy presente nel documento word (copy sito provvisorio EN)
\ggf-dom\8_GGFGROUP\ONMI_AN\SITO HOTEL

**Comment by mauriziocingolani** [comment]
Ok ti ho passato i files (3) su

\ggf-dom\8_GGFGROUP\ONMI_AN\SITO HOTEL\x inglese

**Comment by GiorgioGnoli** [comment]
Ho aggiornato i file nella cartella, lasciando i backup originari. Fammi sapere se vuoi che modifichi anche la privacy in italiano, ma di quella ho paura

**Comment by mauriziocingolani** [comment]
Ok domani mattina carico la versione inglese

**Comment by GiorgioGnoli** [comment]
Ti ho inviato un meta title tradotto male (da me)
questo è quello corretto
SeePort Hotel Ancona | New 4 Stars Business Hotel in Ancona, in the Marche Region
