### ISSUE TITLE
Selettore lingua

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#52]

**Comment by GiorgioGnoli** [comment]
Mauri ti segnalo anche da cambiare la linguetta PRENOTA con BOOK NOW

io metterei a sinistra della linguetta le 2 scritte IT e EN

**Comment by LetiGale** [comment]
Mauri Guido ha approvato il bottone per la scelta della lingua... lo inserisci anche sul sito italiano? grazie
