### ISSUE TITLE
Aumentare font sezione Contatti e inserire numero civico

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#59]
Possiamo aumentare di un paio di pixel il font della sezione contatti?

"Per contattare il SeePort Hotel compila il form seguente
h24
+39 071 9715101
+39 071 2850310
info@seeporthotel.com
www.seeporthotel.com
Rupi di Via XXIX Settembre, Ancona"

Inserire poi il civico 12 dopo Settembre (Rupi di Via XXIX Settembre 12, Ancona)

e scrivere in grassetto il numero di telefono e la mail...

so a cosa stai pensando e sono d'accordo con te

**Comment by LetiGale** [comment]
mauri non ho il tuo numero.. Giorgio mi dice se almeno puoi scriverlo in nero invece che grigio ed utilizzare il grassetto...

**Comment by mauriziocingolani** [comment]
Fatto. Vedete se va meglio

**Comment by LetiGale** [comment]
Puoi fare anche mail e sito internet nero? grazie..
