### ISSUE TITLE
Popup per promozione capodanno

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#61]
http://dinbror.dk/bpopup/
del 3. TRANSITIONS vanno bene entrambi
poi ti faccio avere l'immagine con link (https://secure.hermeshotels.com/bol/pack.do?CA=239&hotel=1986&pack=0&lang=2) 
che va lì dentro appena Grace me la manda

**Comment by GiorgioGnoli** [comment]
![pacchetto capodanno](https://cloud.githubusercontent.com/assets/9283377/5486511/be33749e-86a7-11e4-940f-d2c6e6bc7724.jpg)

Il testo che vorrei metter sotto l'immagine è

Trascorri un indimenticabile Capodanno 2015 al SeePort Hotel
Gran Cenone di Gala in stile Grand Hotel con intrattenimento musicale Jazz, nella splendida sala del Ginevra Restaurant.
Per vedere l’offerta Cenone + soggiorno di 1 o 2 notti, consulta il Pacchetto Capodanno 2015(https://secure.hermeshotels.com/bol/pack.do?CA=239&hotel=1986&pack=0&lang=2).

Farei durare il popup 8 secondi (se possibile), altrimenti facciamo uscire l'utente direttamente quando clicca fuori dal popup o sul bottone di chiusura

**Comment by LetiGale** [comment]
![capodanno 2015](https://cloud.githubusercontent.com/assets/9284701/5487699/1e48e2b2-86b5-11e4-8cbd-98d262ea57bc.jpg)
