### ISSUE TITLE
Cambiare title

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#67]
Sostituire "SeePort Hotel Ancona 4 Stelle | Nuovo Hotel Marche Business"
con "SeePort Hotel Ancona 4 stelle | Nuovo Hotel nel centro di Ancona, Marche"

**Comment by mauriziocingolani** [comment]
Mi dai anche quello inglese?
Grazie

**Comment by GiorgioGnoli** [comment]
SeePort Ancona 4 stars Hotel | New hotel in the center of Ancona, Marche Region
