### ISSUE TITLE
Popup promozione San Valentino

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#68]
Come per Capodanno dobbiamo mettere su un popup per la promozione del San Valentino

"San Valentino al SeePort Hotel - Il piacere dei sensi
Vivi una serata romantica all'insegna del gusto e della musica, nella splendida cornice del Ginevra Restaurant, sul Porto di Ancona.
Approfitta dell’offerta <strong>Cena Gourmet + soggiorno di 1 notte</strong> al SeePort Hotel: vedi il Pacchetto San Valentino (https://secure.hermeshotels.com/bol/pack.do?CA=239&hotel=1986&pack=0&lang=2).

St. Valentine at SeePort Hotel - The pleasure of the senses
Live a romantic evening full of taste and music in the beautiful setting of the Geneva Restaurant, on the Port of Ancona.
Take advantage of  the Valentine's proposal: <strong>Gourmet Dinner + 1 night stay</strong> at  SeePort Hotel! Discover our offer on: (https://secure.hermeshotels.com/bol/pack.do?CA=239&hotel=1986&pack=0&lang=1)

![san valentino_flyer a4 _menu](https://cloud.githubusercontent.com/assets/9283377/5859433/6f29598a-a25a-11e4-9e50-ffe0bb449514.jpg)

usiamo pure la foto x tutte e 2 le lingue, per il tedesco lasciamo il link all'inglese.

**Comment by mauriziocingolani** [comment]
Ok fatto, vedi se va bene.
E' visibile solo internamente e viene su sempre, quando mi dai l'ok lo pubblico e ripristino il meccanismo di comparsa.

**Comment by GiorgioGnoli** [comment]
Purtroppo non mi si vede il testo perché l'immagine copre tutta la schermata. Proviamo a ridurre l'immagine?
![san valentino](https://cloud.githubusercontent.com/assets/9283377/5871657/18117920-a2e1-11e4-9804-a67e80d335a6.JPG)

**Comment by mauriziocingolani** [comment]
Meglio? (vedi solo italiano)

**Comment by GiorgioGnoli** [comment]
Si va bene così. Solo 2 cose
- scriverei <h2>San Valentino al SeePort Hotel - Il Piacere dei sensi</h2> (con anche la P di piacere maiuscola), se è possibile lo metterei come titolo che così è già in grassetto e di dimensioni più grandi rispetto al resto del testo
- leverei vedi il Pacchetto San Valentino, perché abbiamo già il bottone maggiori informazioni e linkano nella stessa pagina

**Comment by mauriziocingolani** [comment]
Vedi se basta come grandezza

**Comment by GiorgioGnoli** [comment]
![cattura](https://cloud.githubusercontent.com/assets/9283377/5872286/1254bf48-a2ea-11e4-9d84-4aea8132f040.JPG)
Si vede un po' bassino, se riusciamo a portarlo un po' più in alto si vede anche il bottone, come dimensione comunque va bene

**Comment by GiorgioGnoli** [comment]
scusa come non detto, ho riaggiornato e mi è apparso in alto ;) grazie possiamo metterlo online

**Comment by mauriziocingolani** [comment]
Ok online in tutte e 3 le lingue
