### ISSUE TITLE
Google map via javascript

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#7]

**Comment by GiorgioGnoli** [comment]
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2888.5448308882897!2d13.506616399999993!3d43.61601800000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132d7fa2928e8627%3A0xc224ae51fe843cd7!2sVia+Rupi+di+Via+XXIX+Settembre%2C+Ancona!5e0!3m2!1sit!2sit!4v1413903124642" width="600" height="450" frameborder="0" style="border:0"></iframe>

questo è il frame da inserire nel sito. Purtroppo non c'è numero civico nell'hotel. Appena avremo il place inseriremo quello. Domattina apriremo la richiesta

**Comment by GiorgioGnoli** [comment]
iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2888.5448308882897!2d13.506616399999993!3d43.61601800000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132d7fa2928e8627%3A0xc224ae51fe843cd7!2sVia+Rupi+di+Via+XXIX+Settembre%2C+Ancona!5e0!3m2!1sit!2sit!4v1413903124642" width="600" height="450" frameborder="0" style="border:0"></iframe
