### ISSUE TITLE
Cambiare popup di san valentino con quello oriental fusion

### ISSUE THREAD

**Issue by SilviaVernelliGGF** [mauriziocingolani/seeport#70]
ITA
Un mix di sapori dall'Oriente sapientemente coniugati con gli ingredienti del nostro territorio dal nostro chef Giordano Calcina, dalla decennale esperienza in Oriente,dalla Thailandia a Taipei.

Per info contattate il numero
0719715100
o scrivete all'indirizzo
(mailto)info@seeporthotel.com

Non perdete l'evento su Facebook cliccando qui (https://www.facebook.com/events/1556355317937377/), invitando anche i vostri amici!

Maggiori informazioni linkerà alla mail

ENG
A mix of flavors from the East expertly blended with the ingredients of our land by our chef Giordano Calcina, from decades of experience in the East, from Thailand to Taipei.
For info, please contact the number
0719715100
or write to
(mailto:)info@seeporthotel.com
Do not miss the event on Facebook by clicking here (https://www.facebook.com/events/1556355317937377/) and invite your friends!

More information linkerà alla mail

Per il momento lasciamo solo italiano e inglese
![pacchetto seeport](https://cloud.githubusercontent.com/assets/10738440/5934933/ceca44e2-a6d5-11e4-947b-de6ca6b4e143.jpg)

**Comment by GiorgioGnoli** [comment]
Feedback dal marketing: cambiamo "del nostro territorio" con "del territorio"
in inglese lasciamo uguale 
poi puoi pubblicare ;)
grazie
