### ISSUE TITLE
Titolo e descrizione russi

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#73]
Mi sa che nella traduzione (o nella trasformazione dei caratteri in entità html) c'è qualcosa che non va (4 stelle è diventato 4x)

**Comment by GiorgioGnoli** [comment]
chiamato in hotel. 
non mi ha risposto nessuno..
mando adesso una mail con il link al sito e spiegando il problema specifico, ma me li aveva mandati così lei
