### ISSUE TITLE
Sezione contatti russa

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#74]
Nella form italiana c'è il link su "informativa sulla privacy". A quali parole russe corrisponde?

**Comment by mauriziocingolani** [comment]
La finestra che si apre cliccando sul link va tradotta? Per ora ho messo quella inglese

**Comment by GiorgioGnoli** [comment]
конфиденциальн dovrebbe essere privacy quindi linkerei a quella.
Lasciamo tutto in inglese per quella parte
