### ISSUE TITLE
Messaggi di errore russi

### ISSUE THREAD

**Issue by mauriziocingolani** [mauriziocingolani/seeport#75]
Andrebbero tradotte queste frasi:

Inserisci il tuo nome e cognome.
Inserisci il tuo indirizzo email.
Inserisci un indirizzo email valido.
Inserisci il tuo messaggio (almeno 10 caratteri).
Devi acconsentire al trattamento dei dati.

**Comment by GiorgioGnoli** [comment]
Ho girato la richiesta di traduzione, Aliona viene oggi alle 5. Per ora lascerei quelli in inglese

**Comment by GiorgioGnoli** [comment]
inviati via mail
Ha detto Aliona che ha controllato il sito ed è tutto ok
