### ISSUE TITLE
verifica webmaster tools seeport

### ISSUE THREAD

**Issue by GiorgioGnoli** [mauriziocingolani/seeport#77]
Mauri mi sa che mi è saltato il wmt del seeport, con GA non riesco a verificarlo, fammi sapere che codice posso mandarti per la verifica

**Comment by mauriziocingolani** [comment]
Io ho la verifica tramite file: google29d3509e94d4fd4c.html

**Comment by GiorgioGnoli** [comment]
allora mi sa che è saltato quello, mi dicono di inserire questo..
 google467ede56b17a8092.html

**Comment by mauriziocingolani** [comment]
Ok, ma mi serve il file, non solo il nome ;-)

**Comment by GiorgioGnoli** [comment]
infatti sì..:) 
mandato via mail
